name = "bankshot"
compatibility_date = "2026-06-23"
pages_build_output_dir = "dist"

[vars]
BANKSHOT_TIME_ZONE = "America/Los_Angeles"

[[kv_namespaces]]
binding = "PUZZLES_KV"
id = "d61736bb768c4bc8ae7e5b2d0f475b41"
preview_id = "d61736bb768c4bc8ae7e5b2d0f475b41"